spring:
  rabbitmq:
    addresses: 10.162.118.225:5672
    username: root
    password: aA111111
    virtual-host: /
    connection-timeout: 15000

server:
  servlet:
    context-path: /
  port: 8002
