apiVersion: v1
# 多pod模式，和pod_nginx里的Pod进行区分
kind: ReplicationController 
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: hub.c.163.com/library/nginx
        ports:
        - containerPort: 80
